# Generated by Django 5.2.4 on 2025-07-29 14:56

import django.db.models.deletion
import wines.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("wine_type", models.CharField(blank=True, max_length=100)),
                ("abv", models.FloatField(blank=True, null=True)),
                ("vintage", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("grape", models.CharField(blank=True, max_length=100)),
                ("characteristics", models.TextField(blank=True)),
                ("style", models.CharField(blank=True, max_length=100)),
                ("capacity", models.FloatField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wines.models.wine_image_file_path,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "vintage", "capacity"),
                        name="unique_wine_entry",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WineReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="wines.wine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("wine", "user")},
            },
        ),
    ]
