# Generated by Django 5.2.4 on 2025-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("wine_type", models.CharField(blank=True, max_length=100)),
                ("abv", models.FloatField(blank=True, null=True)),
                ("vintage", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("grape", models.CharField(blank=True, max_length=100)),
                ("characteristics", models.TextField(blank=True)),
                ("style", models.CharField(blank=True, max_length=100)),
                ("capacity", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
