# Generated by Django 5.2.4 on 2025-08-07 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winereview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Оцінка від 0 до 10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
