# Generated by Django 5.2.4 on 2025-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="vintage",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
    ]
