# Generated by Django 5.2.4 on 2025-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0002_alter_wine_vintage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
