# Generated by Django 5.2.4 on 2025-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0003_alter_wine_price"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wine",
            constraint=models.UniqueConstraint(
                fields=("title", "vintage", "capacity"), name="unique_wine_entry"
            ),
        ),
    ]
