# Generated by Django 5.2.4 on 2025-07-21 12:16

import wines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0004_wine_unique_wine_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wine",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="wine",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=wines.models.wine_image_file_path
            ),
        ),
    ]
