# Generated by Django 5.2.4 on 2025-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0001_initial"),
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_wines",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by_users", to="wines.wine"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
